
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target "设计模式" do 
 
pod 'Aspects'
pod 'MLeaksFinder'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'CTMediator'
pod 'KVOController'
pod 'ZFPlayer', '~> 4.0'

end
